src/Entity/Artiest.php
<?php

namespace App\Entity;

use App\Repository\ArtiestRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArtiestRepository::class)
 */
class Artiest
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $naam;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $genre;

    /**
     * @ORM\Column(type="string", length=400)
     */
    private $omschrijving;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $afbeelding_url;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $website;

    /**
     * @ORM\OneToMany(targetEntity=Optreden::class, mappedBy="artiest")
     */
    private $Optreden;

    public function __construct()
    {
        $this->Optreden = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNaam(): ?string
    {
        return $this->naam;
    }

    public function setNaam(string $naam): self
    {
        $this->naam = $naam;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(string $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    public function getOmschrijving(): ?string
    {
        return $this->omschrijving;
    }

    public function setOmschrijving(string $omschrijving): self
    {
        $this->omschrijving = $omschrijving;

        return $this;
    }

    public function getAfbeeldingUrl(): ?string
    {
        return $this->afbeelding_url;
    }

    public function setAfbeeldingUrl(string $afbeelding_url): self
    {
        $this->afbeelding_url = $afbeelding_url;

        return $this;
    }

    public function getWebsite(): ?string
    {
        return $this->website;
    }

    public function setWebsite(string $website): self
    {
        $this->website = $website;

        return $this;
    }

    /**
     * @return Collection|Optreden[]
     */
    public function getOptreden(): Collection
    {
        return $this->Optreden;
    }

    public function addOptreden(Optreden $optreden): self
    {
        if (!$this->Optreden->contains($optreden)) {
            $this->Optreden[] = $optreden;
            $optreden->setArtiest($this);
        }

        return $this;
    }

    public function removeOptreden(Optreden $optreden): self
    {
        if ($this->Optreden->removeElement($optreden)) {
            // set the owning side to null (unless already changed)
            if ($optreden->getArtiest() === $this) {
                $optreden->setArtiest(null);
            }
        }

        return $this;
    }
}

src/Entity/Optreden.php
<?php

namespace App\Entity;

use App\Repository\OptredenRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OptredenRepository::class)
 */
class Optreden
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Poppodium::class, inversedBy="Optredens")
     * @ORM\JoinColumn(nullable=false)
     */
    private $poppodium;

    /**
     * @ORM\ManyToOne(targetEntity=Artiest::class, inversedBy="Optreden")
     * @ORM\JoinColumn(nullable=false)
     */
    private $artiest;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $omschrijving;

    /**
     * @ORM\Column(type="datetime")
     */
    private $datum;

    /**
     * @ORM\Column(type="integer")
     */
    private $prijs;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ticket_url;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $afbeelding_url;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPoppodium(): ?Poppodium
    {
        return $this->poppodium;
    }

    public function setPoppodium(?Poppodium $poppodium): self
    {
        $this->poppodium = $poppodium;

        return $this;
    }

    public function getArtiest(): ?Artiest
    {
        return $this->artiest;
    }

    public function setArtiest(?Artiest $artiest): self
    {
        $this->artiest = $artiest;

        return $this;
    }

    public function getOmschrijving(): ?string
    {
        return $this->omschrijving;
    }

    public function setOmschrijving(string $omschrijving): self
    {
        $this->omschrijving = $omschrijving;

        return $this;
    }

    public function getDatum(): ?\DateTimeInterface
    {
        return $this->datum; 
    }

    public function setDatum(\DateTimeInterface $datum): self
    {
        $this->datum = $datum;

        return $this;
    }

    public function getPrijs(): ?int
    {
        return $this->prijs;
    }

    public function setPrijs(int $prijs): self
    {
        $this->prijs = $prijs;

        return $this;
    }

    public function getTicketUrl(): ?string
    {
        return $this->ticket_url;
    }

    public function setTicketUrl(string $ticket_url): self
    {
        $this->ticket_url = $ticket_url;

        return $this;
    }

    public function getAfbeeldingUrl(): ?string
    {
        return $this->afbeelding_url;
    }

    public function setAfbeeldingUrl(string $afbeelding_url): self
    {
        $this->afbeelding_url = $afbeelding_url;

        return $this;
    }
}

src/Controller/HomePageController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use App\Entity\Optreden;

    /**
     * @Route("/")
     */

class HomePageController extends AbstractController
{
    /**
     * @Route("/", name="home_page")
     * @Template()
     */
    public function index()
    {

        $rep = $this->getDoctrine()->getRepository(Optreden::class);
        $data = $rep->getAllOptredens();

        return(["data" => $data, "page_title" => 'Home']);
    }

    /**
     * @Route("/optreden/show/{id}", name="optreden_show")
     * @Template()
     */

    public function showOptreden($id) {

        $rep = $this->getDoctrine()->getRepository(Optreden::class);
        $data = $rep->getOptreden($id);


        return(["optreden" => $data, "page_title" => $data->getArtiest()->getNaam()]);
     }

     public function saveOptreden($params) {

        $rep = $this->getDoctrine()->getRepository(Optreden::class);
        $data = $rep->saveOptreden($params);

     }


}

templates/home_page/index.html.twig
{% extends 'base.html.twig' %}


{% block body %}


<div class="container-fluid mb_8">
    {% for optreden in data %}
            <div class="optreden row d-flex mb-5 p-md-5 p-4">
                {# <h2>{{ dump(optreden) }}</h2> #}
                <div class="col-md-4 col-12 text-start">
                    <div class="optreden__content">
                        <h1 style="line-height:54px;">{{ optreden.artiest.naam }}</h1>
                        <p>{{ optreden.datum|date('D d M Y') }}</p>
                    </div>
                </div>
                <div class="col-md-8 col-12 optreden__img text-end">
                    <a href={{ path('optreden_show', { "id": optreden.id }) }}><img class="arrow__item" src="{{ asset('assets/img/iconmonstr-arrow-20.svg') }}"/></a>
                    <img class="img__item mt-3 mt-md-0" src="{{ optreden.afbeeldingUrl }}"/> 
                </div>
            </div>
    {% endfor %}
</div>

{% endblock %}

templates/home_page/show_optreden.html.twig
{% extends 'base.html.twig' %}



{% block body %}

<div class="container-fluid">
<div class="mx-auto wrapper__optreden__show  my-2 my-md-5">

    {# <div>
        <h2>{{dump(optreden)}}</h2>
    </div> #}
    <a href="{{ path('programma_list') }}" style="color:grey;">< terug naar programma</a>

    <div class="optreden__show">
        <img class="img__itemshow" src="{{ optreden.afbeeldingUrl }}"/> 
    </div>


    <div class="container">

        <div class="itemshow__content row">

            <div class="col-md-8">
                <h1 class="mb-5">{{ optreden.artiest.naam }}</h1>
                <h3  class="mb-3">{{ optreden.datum|date('D d M Y') }}</h3>
                <p><strong>{{optreden.poppodium.naam}}</strong></p>
                <p>{{ optreden.poppodium.adres }}</br>{{ optreden.poppodium.postcode }} {{ optreden.poppodium.woonplaats }}</p>
                <h3 class="mt-5">Aanvang: {{ optreden.datum|date('H:i') }} uur</h3>
                <p class="mt-5"><strong>{{optreden.omschrijving}}</strong></p>
                <p class="my-2">{{optreden.artiest.omschrijving}}</p>
            </div>

            <div class="col-md-4 text-md-end p-3">
                <a class="btn btn-lg button__koop mb-3" href="{{optreden.ticketUrl}}"><p>KOOP TICKETS</p></a>
                <p>Prijs €{{optreden.prijs}}</p>
            </div>

        </div>

    </div>
</div>
</div>

{% endblock %}